export enum SectionENUM {
  ARTS = "arts",
  MOVIES = "movies",
  FOOD = "food",
  STYLE = "style",
  WORLD = "world",
  AUTOMOBILES = "automobiles",
  BOOKS = "books",
  CLIMATE = "climate",
  EDUCATION = "education",
  HEATH = "health",
  SCIENCE = "science",
  SPORTS = "sports",
  TECHNOLOGY = "technology",
  THEATER = "theater",
  TRAVEL = "travel",
  UNIVERSAL = "universal",
  ALL = "all",
}
